### PR TITLE
Feat: Page to view single video

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following-
- User can click on a video and they are navigated to a new page
- On the single video viewing page user can add the video to likes, watch later or add it to a playlist.
- Can read the description, creator and other details of the video

### CODE REVIEW

**Review by jeetbhalani15 — APPROVED** [review]
Video context & Reducer Code looks good
- Overall code is clean
- UI looks good Cant login with guest id have a look

**Comment by bharati-21** [comment]
> Video context & Reducer Code looks good
> 
> * Overall code is clean
> * UI looks good Cant login with guest id have a look

Thank you for informing and for your review. I shall look into it.

**Review by SHIKHASINGH1506 — APPROVED** [review]
1. I like how you've done error handling
2. Nothing major caught my eyes 
3. It can be merged

**Comment by bharati-21** [comment]
> 1. I like how you've done error handling
> 2. Nothing major caught my eyes
> 3. It can be merged

Thank you for your review.

**Pull request merged**
