### PR TITLE
Feat: Filter, sort, and search videos

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following features:
- Users can search for videos based on title from the search bar on the navbar. On submitting, they are navigated to the explore (if they are already not there) page with the videos filtered based on search text.
- Users can click on any category chips on the explore page and the videos are filtered and displayed based on category.
- Users can also sort videos based on upload date - either by earliest or oldest upload date.

### CODE REVIEW

**Review by simran61 — APPROVED** [review]
Looks good
Nice UI
Easily readable code

**Review by MonikaJhingan — APPROVED** [review]
The code is well documented and the Ui looks amazing .Plse merge it.

**Comment by bharati-21** [comment]
> Looks good Nice UI Easily readable code

Thank you for review.

**Comment by bharati-21** [comment]
> The code is well documented and the Ui looks amazing .Plse merge it.

Thank you for review.

**Pull request merged**
