### PR TITLE
feat: Home page

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following features
- components to display header, navbar, footer
- Home Page with  header and video categories listed
- Basic explore page
- Theme context to change and set theme
- responsive navbar
- Categories context that fetched categories from mock backend

image
image
image
image

### CODE REVIEW

**Review by manojasarsa — APPROVED** [review]
The UI is looking amazing and the code seems clean and readable.
Good work, Bharati!

**Review by mcmonojit — APPROVED** [review]
Very clean code. Looks good to merge.

**Comment by bharati-21** [comment]
> The UI is looking amazing and the code seems clean and readable. Good work, Bharati!

Thank you for your review.

**Comment by bharati-21** [comment]
> Very clean code. Looks good to merge.

Thank you for your review.

**Pull request merged**
