### PR TITLE
feat: added authentication

### PR DESCRIPTION
**Pull request by bharati-21**
This PR contains the following-
- added login, sign up pages
- login and signup service handlers to post to backend
- routes
- protected routes

### CODE REVIEW

**Review by manojasarsa — APPROVED** [review]
Code looks clean and self-explanatory.
GTG!

**Review by devananth — APPROVED** [review]
- Code looks clean and well structured
- UI looks clean 
- Good Work !

**Comment by bharati-21** [comment]
> Code looks clean and self-explanatory. GTG!

Thank you for your review.

**Comment by bharati-21** [comment]
> * Code looks clean and well structured
> * UI looks clean
> * Good Work !

Thank you for your review.

**Pull request merged**
